name: ispot
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.0.0-nullsafety.2
  gql_http_link: ^0.3.2

  ferry_hive_store: ^0.3.2
  hive: ^1.4.4+1
  hive_flutter:
  flutter_icons: ^1.1.0
  flutter_swiper: ^1.1.6
  animations: ^2.0.0
  chips_choice: ^2.0.1
  reactive_forms: ^9.1.0
  badges: ^1.1.4
  ripple_effect: ^0.1.1
  flutter_staggered_grid_view: ^0.3.2
  dartz: ^0.9.2
  carousel_slider: ^3.0.0
  shimmer: ^1.1.2
  backdrop: ^0.6.0
  ferry: ^0.9.1
  get_storage: ^2.0.1
  url_launcher: ^6.0.2
  path_provider: ^2.0.1
  modal_bottom_sheet: ^2.0.0
  gql_error_link: ^0.1.1-alpha+1612972259650
  gql_transform_link: ^0.1.5
  number_display:
  auto_size_text: ^2.1.0
  splashscreen: ^1.3.5
  skeleton_loader: ^1.0.2+3

dev_dependencies:
  build_runner:
  ferry_generator:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/no-photo.png
    - assets/brand-logo.png
    - assets/no-data.png

dependency_overrides:
  file_testing: ^2.0.3
  analyzer: ^0.41.1
