name: ispot
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  get: ^3.24.0
  gql_http_link: ^0.2.9

  ferry_hive_store: ^0.3.2
  hive: ^1.4.4+1
  hive_flutter:
  flutter_icons: ^1.1.0
  flutter_swiper: ^1.1.6
  animations: ^1.1.2
  chips_choice: ^2.0.1
  reactive_forms: ^6.0.4
  badges: ^1.1.4
  ripple_effect: ^0.1.1
  flutter_staggered_grid_view: ^0.3.2
  dartz: ^0.9.2
  carousel_slider: ^2.3.1
  shimmer: ^1.1.2
  backdrop: ^0.4.7
  ferry: ^0.9.1
  get_storage: ^1.4.0
  url_launcher: ^5.7.10
  path_provider: ^1.6.24
  modal_bottom_sheet: ^1.0.0+1

dev_dependencies:
  build_runner:
  ferry_generator:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/no-photo.png
    - assets/brand-logo.png

dependency_overrides:
  file_testing: ^2.0.3
