// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'serializers.gql.dart';

// **************************************************************************
// BuiltValueGenerator
// **************************************************************************

Serializers _$serializers = (new Serializers().toBuilder()
      ..add(GAccountErrorCode.serializer)
      ..add(GAccountInput.serializer)
      ..add(GAccountRegisterInput.serializer)
      ..add(GAddressInput.serializer)
      ..add(GAddressTypeEnum.serializer)
      ..add(GAppErrorCode.serializer)
      ..add(GAppFilterInput.serializer)
      ..add(GAppInput.serializer)
      ..add(GAppSortField.serializer)
      ..add(GAppSortingInput.serializer)
      ..add(GAppTokenInput.serializer)
      ..add(GAttributeAssignInput.serializer)
      ..add(GAttributeCreateInput.serializer)
      ..add(GAttributeFilterInput.serializer)
      ..add(GAttributeInput.serializer)
      ..add(GAttributeInputTypeEnum.serializer)
      ..add(GAttributeSortField.serializer)
      ..add(GAttributeSortingInput.serializer)
      ..add(GAttributeTypeEnum.serializer)
      ..add(GAttributeUpdateInput.serializer)
      ..add(GAttributeValueCreateInput.serializer)
      ..add(GAttributeValueInput.serializer)
      ..add(GAttributeValueType.serializer)
      ..add(GAuthorizationKeyInput.serializer)
      ..add(GAuthorizationKeyType.serializer)
      ..add(GBasicProductFieldsData.serializer)
      ..add(GBasicProductFieldsData_thumbnail.serializer)
      ..add(GBasicProductFieldsReq.serializer)
      ..add(GBasicProductFieldsVars.serializer)
      ..add(GCatalogueInput.serializer)
      ..add(GCategoryData.serializer)
      ..add(GCategoryData_attributes.serializer)
      ..add(GCategoryData_attributes_edges.serializer)
      ..add(GCategoryData_attributes_edges_node.serializer)
      ..add(GCategoryData_attributes_edges_node_values.serializer)
      ..add(GCategoryData_category.serializer)
      ..add(GCategoryData_category_ancestors.serializer)
      ..add(GCategoryData_category_ancestors_edges.serializer)
      ..add(GCategoryData_category_ancestors_edges_node.serializer)
      ..add(GCategoryData_category_backgroundImage.serializer)
      ..add(GCategoryData_products.serializer)
      ..add(GCategoryData_products_edges.serializer)
      ..add(GCategoryData_products_edges_node.serializer)
      ..add(GCategoryData_products_edges_node_images.serializer)
      ..add(GCategoryData_products_edges_node_pricing.serializer)
      ..add(GCategoryData_products_edges_node_pricing_priceRange.serializer)
      ..add(
          GCategoryData_products_edges_node_pricing_priceRange_start.serializer)
      ..add(GCategoryData_products_edges_node_pricing_priceRange_start_net
          .serializer)
      ..add(
          GCategoryData_products_edges_node_pricing_priceRange_stop.serializer)
      ..add(GCategoryData_products_edges_node_pricing_priceRange_stop_net
          .serializer)
      ..add(GCategoryData_products_edges_node_thumbnail.serializer)
      ..add(GCategoryData_products_pageInfo.serializer)
      ..add(GCategoryFilterInput.serializer)
      ..add(GCategoryInput.serializer)
      ..add(GCategoryListData.serializer)
      ..add(GCategoryListData_categories.serializer)
      ..add(GCategoryListData_categories_edges.serializer)
      ..add(GCategoryListData_categories_edges_node.serializer)
      ..add(GCategoryListData_categories_edges_node_backgroundImage.serializer)
      ..add(GCategoryListData_categories_pageInfo.serializer)
      ..add(GCategoryListReq.serializer)
      ..add(GCategoryListVars.serializer)
      ..add(GCategoryReq.serializer)
      ..add(GCategorySortField.serializer)
      ..add(GCategorySortingInput.serializer)
      ..add(GCategoryVars.serializer)
      ..add(GCheckoutCreateInput.serializer)
      ..add(GCheckoutErrorCode.serializer)
      ..add(GCheckoutLineInput.serializer)
      ..add(GCollectionCreateInput.serializer)
      ..add(GCollectionData.serializer)
      ..add(GCollectionData_collection.serializer)
      ..add(GCollectionData_collection_backgroundImage.serializer)
      ..add(GCollectionData_products.serializer)
      ..add(GCollectionData_products_edges.serializer)
      ..add(GCollectionData_products_edges_node.serializer)
      ..add(GCollectionData_products_edges_node_images.serializer)
      ..add(GCollectionData_products_edges_node_pricing.serializer)
      ..add(GCollectionData_products_edges_node_pricing_priceRange.serializer)
      ..add(GCollectionData_products_edges_node_pricing_priceRange_start
          .serializer)
      ..add(GCollectionData_products_edges_node_pricing_priceRange_start_net
          .serializer)
      ..add(GCollectionData_products_edges_node_pricing_priceRange_stop
          .serializer)
      ..add(GCollectionData_products_edges_node_pricing_priceRange_stop_net
          .serializer)
      ..add(GCollectionData_products_edges_node_thumbnail.serializer)
      ..add(GCollectionData_products_pageInfo.serializer)
      ..add(GCollectionFilterInput.serializer)
      ..add(GCollectionInput.serializer)
      ..add(GCollectionPublished.serializer)
      ..add(GCollectionReq.serializer)
      ..add(GCollectionSortField.serializer)
      ..add(GCollectionSortingInput.serializer)
      ..add(GCollectionVars.serializer)
      ..add(GCollectionsData.serializer)
      ..add(GCollectionsData_collections.serializer)
      ..add(GCollectionsData_collections_edges.serializer)
      ..add(GCollectionsData_collections_edges_node.serializer)
      ..add(GCollectionsData_collections_edges_node_backgroundImage.serializer)
      ..add(GCollectionsData_collections_pageInfo.serializer)
      ..add(GCollectionsReq.serializer)
      ..add(GCollectionsVars.serializer)
      ..add(GConfigurationItemInput.serializer)
      ..add(GConfigurationTypeFieldEnum.serializer)
      ..add(GCountryCode.serializer)
      ..add(GCustomerEventsEnum.serializer)
      ..add(GCustomerFilterInput.serializer)
      ..add(GCustomerInput.serializer)
      ..add(GDate.serializer)
      ..add(GDateRangeInput.serializer)
      ..add(GDateTime.serializer)
      ..add(GDateTimeRangeInput.serializer)
      ..add(GDecimal.serializer)
      ..add(GDigitalContentInput.serializer)
      ..add(GDigitalContentUploadInput.serializer)
      ..add(GDigitalContentUrlCreateInput.serializer)
      ..add(GDiscountErrorCode.serializer)
      ..add(GDiscountStatusEnum.serializer)
      ..add(GDiscountValueTypeEnum.serializer)
      ..add(GDraftOrderCreateInput.serializer)
      ..add(GDraftOrderInput.serializer)
      ..add(GFeaturedProductsData.serializer)
      ..add(GFeaturedProductsData_shop.serializer)
      ..add(GFeaturedProductsData_shop_homepageCollection.serializer)
      ..add(GFeaturedProductsData_shop_homepageCollection_backgroundImage
          .serializer)
      ..add(GFeaturedProductsData_shop_homepageCollection_products.serializer)
      ..add(GFeaturedProductsData_shop_homepageCollection_products_edges
          .serializer)
      ..add(GFeaturedProductsData_shop_homepageCollection_products_edges_node
          .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_category
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_start
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_start_net
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_stop
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_stop_net
              .serializer)
      ..add(
          GFeaturedProductsData_shop_homepageCollection_products_edges_node_thumbnail
              .serializer)
      ..add(GFeaturedProductsReq.serializer)
      ..add(GFeaturedProductsVars.serializer)
      ..add(GFulfillmentCancelInput.serializer)
      ..add(GFulfillmentStatus.serializer)
      ..add(GFulfillmentUpdateTrackingInput.serializer)
      ..add(GGenericScalar.serializer)
      ..add(GGiftCardCreateInput.serializer)
      ..add(GGiftCardErrorCode.serializer)
      ..add(GGiftCardUpdateInput.serializer)
      ..add(GIntRangeInput.serializer)
      ..add(GJSONString.serializer)
      ..add(GLanguageCodeEnum.serializer)
      ..add(GMenuCreateInput.serializer)
      ..add(GMenuErrorCode.serializer)
      ..add(GMenuFilterInput.serializer)
      ..add(GMenuInput.serializer)
      ..add(GMenuItemCreateInput.serializer)
      ..add(GMenuItemFilterInput.serializer)
      ..add(GMenuItemInput.serializer)
      ..add(GMenuItemMoveInput.serializer)
      ..add(GMenuItemSortingInput.serializer)
      ..add(GMenuItemsSortField.serializer)
      ..add(GMenuSortField.serializer)
      ..add(GMenuSortingInput.serializer)
      ..add(GMetaInput.serializer)
      ..add(GMetaPath.serializer)
      ..add(GMetadataErrorCode.serializer)
      ..add(GMetadataInput.serializer)
      ..add(GMoveProductInput.serializer)
      ..add(GNameTranslationInput.serializer)
      ..add(GNavigationType.serializer)
      ..add(GOrderAction.serializer)
      ..add(GOrderAddNoteInput.serializer)
      ..add(GOrderDirection.serializer)
      ..add(GOrderDraftFilterInput.serializer)
      ..add(GOrderErrorCode.serializer)
      ..add(GOrderEventsEmailsEnum.serializer)
      ..add(GOrderEventsEnum.serializer)
      ..add(GOrderFilterInput.serializer)
      ..add(GOrderFulfillInput.serializer)
      ..add(GOrderFulfillLineInput.serializer)
      ..add(GOrderFulfillStockInput.serializer)
      ..add(GOrderLineCreateInput.serializer)
      ..add(GOrderLineInput.serializer)
      ..add(GOrderSortField.serializer)
      ..add(GOrderSortingInput.serializer)
      ..add(GOrderStatus.serializer)
      ..add(GOrderStatusFilter.serializer)
      ..add(GOrderUpdateInput.serializer)
      ..add(GOrderUpdateShippingInput.serializer)
      ..add(GPageErrorCode.serializer)
      ..add(GPageFilterInput.serializer)
      ..add(GPageInput.serializer)
      ..add(GPageSortField.serializer)
      ..add(GPageSortingInput.serializer)
      ..add(GPageTranslationInput.serializer)
      ..add(GPaymentChargeStatusEnum.serializer)
      ..add(GPaymentErrorCode.serializer)
      ..add(GPaymentInput.serializer)
      ..add(GPermissionEnum.serializer)
      ..add(GPermissionGroupCreateInput.serializer)
      ..add(GPermissionGroupErrorCode.serializer)
      ..add(GPermissionGroupFilterInput.serializer)
      ..add(GPermissionGroupSortField.serializer)
      ..add(GPermissionGroupSortingInput.serializer)
      ..add(GPermissionGroupUpdateInput.serializer)
      ..add(GPluginErrorCode.serializer)
      ..add(GPluginFilterInput.serializer)
      ..add(GPluginSortField.serializer)
      ..add(GPluginSortingInput.serializer)
      ..add(GPluginUpdateInput.serializer)
      ..add(GPriceData.serializer)
      ..add(GPriceData_net.serializer)
      ..add(GPriceRangeInput.serializer)
      ..add(GPriceReq.serializer)
      ..add(GPriceVars.serializer)
      ..add(GProductCreateInput.serializer)
      ..add(GProductDetailsData.serializer)
      ..add(GProductDetailsData_product.serializer)
      ..add(GProductDetailsData_product_attributes.serializer)
      ..add(GProductDetailsData_product_attributes_attribute.serializer)
      ..add(GProductDetailsData_product_attributes_values.serializer)
      ..add(GProductDetailsData_product_category.serializer)
      ..add(GProductDetailsData_product_category_products.serializer)
      ..add(GProductDetailsData_product_category_products_edges.serializer)
      ..add(GProductDetailsData_product_category_products_edges_node.serializer)
      ..add(GProductDetailsData_product_category_products_edges_node_pricing
          .serializer)
      ..add(
          GProductDetailsData_product_category_products_edges_node_pricing_priceRange
              .serializer)
      ..add(
          GProductDetailsData_product_category_products_edges_node_pricing_priceRange_start
              .serializer)
      ..add(
          GProductDetailsData_product_category_products_edges_node_pricing_priceRange_start_net
              .serializer)
      ..add(
          GProductDetailsData_product_category_products_edges_node_pricing_priceRange_stop
              .serializer)
      ..add(
          GProductDetailsData_product_category_products_edges_node_pricing_priceRange_stop_net
              .serializer)
      ..add(GProductDetailsData_product_category_products_edges_node_thumbnail
          .serializer)
      ..add(GProductDetailsData_product_images.serializer)
      ..add(GProductDetailsData_product_pricing.serializer)
      ..add(GProductDetailsData_product_pricing_priceRange.serializer)
      ..add(GProductDetailsData_product_pricing_priceRange_start.serializer)
      ..add(GProductDetailsData_product_pricing_priceRange_start_net.serializer)
      ..add(GProductDetailsData_product_pricing_priceRange_stop.serializer)
      ..add(GProductDetailsData_product_pricing_priceRange_stop_net.serializer)
      ..add(GProductDetailsData_product_thumbnail.serializer)
      ..add(GProductDetailsData_product_variants.serializer)
      ..add(GProductDetailsData_product_variants_attributes.serializer)
      ..add(
          GProductDetailsData_product_variants_attributes_attribute.serializer)
      ..add(GProductDetailsData_product_variants_attributes_values.serializer)
      ..add(GProductDetailsData_product_variants_images.serializer)
      ..add(GProductDetailsData_product_variants_pricing.serializer)
      ..add(GProductDetailsData_product_variants_pricing_price.serializer)
      ..add(GProductDetailsData_product_variants_pricing_priceUndiscounted
          .serializer)
      ..add(GProductDetailsData_product_variants_pricing_priceUndiscounted_net
          .serializer)
      ..add(GProductDetailsData_product_variants_pricing_price_net.serializer)
      ..add(GProductDetailsReq.serializer)
      ..add(GProductDetailsVars.serializer)
      ..add(GProductErrorCode.serializer)
      ..add(GProductFilterInput.serializer)
      ..add(GProductImageCreateInput.serializer)
      ..add(GProductImageUpdateInput.serializer)
      ..add(GProductInput.serializer)
      ..add(GProductOrder.serializer)
      ..add(GProductOrderField.serializer)
      ..add(GProductPricingFieldData.serializer)
      ..add(GProductPricingFieldData_pricing.serializer)
      ..add(GProductPricingFieldData_pricing_priceRange.serializer)
      ..add(GProductPricingFieldData_pricing_priceRange_start.serializer)
      ..add(GProductPricingFieldData_pricing_priceRange_start_net.serializer)
      ..add(GProductPricingFieldData_pricing_priceRange_stop.serializer)
      ..add(GProductPricingFieldData_pricing_priceRange_stop_net.serializer)
      ..add(GProductPricingFieldReq.serializer)
      ..add(GProductPricingFieldVars.serializer)
      ..add(GProductStockFilterInput.serializer)
      ..add(GProductTypeConfigurable.serializer)
      ..add(GProductTypeEnum.serializer)
      ..add(GProductTypeFilterInput.serializer)
      ..add(GProductTypeInput.serializer)
      ..add(GProductTypeSortField.serializer)
      ..add(GProductTypeSortingInput.serializer)
      ..add(GProductVariantBulkCreateInput.serializer)
      ..add(GProductVariantCreateInput.serializer)
      ..add(GProductVariantFieldsData.serializer)
      ..add(GProductVariantFieldsData_attributes.serializer)
      ..add(GProductVariantFieldsData_attributes_attribute.serializer)
      ..add(GProductVariantFieldsData_attributes_values.serializer)
      ..add(GProductVariantFieldsData_images.serializer)
      ..add(GProductVariantFieldsData_pricing.serializer)
      ..add(GProductVariantFieldsData_pricing_price.serializer)
      ..add(GProductVariantFieldsData_pricing_priceUndiscounted.serializer)
      ..add(GProductVariantFieldsData_pricing_priceUndiscounted_net.serializer)
      ..add(GProductVariantFieldsData_pricing_price_net.serializer)
      ..add(GProductVariantFieldsReq.serializer)
      ..add(GProductVariantFieldsVars.serializer)
      ..add(GProductVariantInput.serializer)
      ..add(GReorderInput.serializer)
      ..add(GReportingPeriod.serializer)
      ..add(GSaleFilterInput.serializer)
      ..add(GSaleInput.serializer)
      ..add(GSaleSortField.serializer)
      ..add(GSaleSortingInput.serializer)
      ..add(GSaleType.serializer)
      ..add(GSearchProductsData.serializer)
      ..add(GSearchProductsData_products.serializer)
      ..add(GSearchProductsData_products_edges.serializer)
      ..add(GSearchProductsData_products_edges_node.serializer)
      ..add(GSearchProductsData_products_edges_node_pricing.serializer)
      ..add(
          GSearchProductsData_products_edges_node_pricing_priceRange.serializer)
      ..add(GSearchProductsData_products_edges_node_pricing_priceRange_start
          .serializer)
      ..add(GSearchProductsData_products_edges_node_pricing_priceRange_start_net
          .serializer)
      ..add(GSearchProductsData_products_edges_node_pricing_priceRange_stop
          .serializer)
      ..add(GSearchProductsData_products_edges_node_pricing_priceRange_stop_net
          .serializer)
      ..add(GSearchProductsData_products_edges_node_thumbnail.serializer)
      ..add(GSearchProductsData_products_edges_node_thumbnail2x.serializer)
      ..add(GSearchProductsData_products_pageInfo.serializer)
      ..add(GSearchProductsReq.serializer)
      ..add(GSearchProductsVars.serializer)
      ..add(GSelectedAttributeFieldsData.serializer)
      ..add(GSelectedAttributeFieldsData_attribute.serializer)
      ..add(GSelectedAttributeFieldsData_values.serializer)
      ..add(GSelectedAttributeFieldsReq.serializer)
      ..add(GSelectedAttributeFieldsVars.serializer)
      ..add(GSeoInput.serializer)
      ..add(GServiceAccountFilterInput.serializer)
      ..add(GServiceAccountInput.serializer)
      ..add(GServiceAccountSortField.serializer)
      ..add(GServiceAccountSortingInput.serializer)
      ..add(GServiceAccountTokenInput.serializer)
      ..add(GShippingErrorCode.serializer)
      ..add(GShippingMethodTypeEnum.serializer)
      ..add(GShippingPriceInput.serializer)
      ..add(GShippingZoneCreateInput.serializer)
      ..add(GShippingZoneUpdateInput.serializer)
      ..add(GShopErrorCode.serializer)
      ..add(GShopSettingsInput.serializer)
      ..add(GShopSettingsTranslationInput.serializer)
      ..add(GSiteDomainInput.serializer)
      ..add(GStaffCreateInput.serializer)
      ..add(GStaffMemberStatus.serializer)
      ..add(GStaffNotificationRecipientInput.serializer)
      ..add(GStaffUpdateInput.serializer)
      ..add(GStaffUserInput.serializer)
      ..add(GStockAvailability.serializer)
      ..add(GStockErrorCode.serializer)
      ..add(GStockFilterInput.serializer)
      ..add(GStockInput.serializer)
      ..add(GTaxRateType.serializer)
      ..add(GTransactionError.serializer)
      ..add(GTransactionKind.serializer)
      ..add(GTranslatableKinds.serializer)
      ..add(GTranslationErrorCode.serializer)
      ..add(GTranslationInput.serializer)
      ..add(GUUID.serializer)
      ..add(GUpload.serializer)
      ..add(GUserCreateInput.serializer)
      ..add(GUserSortField.serializer)
      ..add(GUserSortingInput.serializer)
      ..add(GVariantListData.serializer)
      ..add(GVariantListData_productVariants.serializer)
      ..add(GVariantListData_productVariants_edges.serializer)
      ..add(GVariantListData_productVariants_edges_node.serializer)
      ..add(GVariantListData_productVariants_edges_node_attributes.serializer)
      ..add(GVariantListData_productVariants_edges_node_attributes_attribute
          .serializer)
      ..add(GVariantListData_productVariants_edges_node_attributes_values.serializer)
      ..add(GVariantListData_productVariants_edges_node_images.serializer)
      ..add(GVariantListData_productVariants_edges_node_pricing.serializer)
      ..add(GVariantListData_productVariants_edges_node_pricing_price.serializer)
      ..add(GVariantListData_productVariants_edges_node_pricing_priceUndiscounted.serializer)
      ..add(GVariantListData_productVariants_edges_node_pricing_priceUndiscounted_net.serializer)
      ..add(GVariantListData_productVariants_edges_node_pricing_price_net.serializer)
      ..add(GVariantListData_productVariants_edges_node_product.serializer)
      ..add(GVariantListData_productVariants_edges_node_product_thumbnail.serializer)
      ..add(GVariantListReq.serializer)
      ..add(GVariantListVars.serializer)
      ..add(GVoucherDiscountType.serializer)
      ..add(GVoucherFilterInput.serializer)
      ..add(GVoucherInput.serializer)
      ..add(GVoucherSortField.serializer)
      ..add(GVoucherSortingInput.serializer)
      ..add(GVoucherTypeEnum.serializer)
      ..add(GWarehouseAddressInput.serializer)
      ..add(GWarehouseCreateInput.serializer)
      ..add(GWarehouseErrorCode.serializer)
      ..add(GWarehouseFilterInput.serializer)
      ..add(GWarehouseSortField.serializer)
      ..add(GWarehouseSortingInput.serializer)
      ..add(GWarehouseUpdateInput.serializer)
      ..add(GWebhookCreateInput.serializer)
      ..add(GWebhookErrorCode.serializer)
      ..add(GWebhookEventTypeEnum.serializer)
      ..add(GWebhookFilterInput.serializer)
      ..add(GWebhookSampleEventTypeEnum.serializer)
      ..add(GWebhookSortField.serializer)
      ..add(GWebhookSortingInput.serializer)
      ..add(GWebhookUpdateInput.serializer)
      ..add(GWeightScalar.serializer)
      ..add(GWeightUnitsEnum.serializer)
      ..add(G_Any.serializer)
      ..add(GattributesData.serializer)
      ..add(GattributesData_attributes.serializer)
      ..add(GattributesData_attributes_edges.serializer)
      ..add(GattributesData_attributes_edges_node.serializer)
      ..add(GattributesData_attributes_edges_node_values.serializer)
      ..add(GattributesData_attributes_pageInfo.serializer)
      ..add(GattributesReq.serializer)
      ..add(GattributesVars.serializer)
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeInput)]), () => new ListBuilder<GAttributeInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeInput)]), () => new ListBuilder<GAttributeInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueCreateInput)]), () => new ListBuilder<GAttributeValueCreateInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueInput)]), () => new ListBuilder<GAttributeValueInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueInput)]), () => new ListBuilder<GAttributeValueInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GStockInput)]), () => new ListBuilder<GStockInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueInput)]), () => new ListBuilder<GAttributeValueInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GStockInput)]), () => new ListBuilder<GStockInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueInput)]), () => new ListBuilder<GAttributeValueInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueInput)]), () => new ListBuilder<GAttributeValueInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GStockInput)]), () => new ListBuilder<GStockInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCategoryData_attributes_edges)]), () => new ListBuilder<GCategoryData_attributes_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCategoryData_attributes_edges_node_values)]), () => new ListBuilder<GCategoryData_attributes_edges_node_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCategoryData_category_ancestors_edges)]), () => new ListBuilder<GCategoryData_category_ancestors_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCategoryData_products_edges)]), () => new ListBuilder<GCategoryData_products_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCategoryData_products_edges_node_images)]), () => new ListBuilder<GCategoryData_products_edges_node_images>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCategoryListData_categories_edges)]), () => new ListBuilder<GCategoryListData_categories_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCheckoutLineInput)]), () => new ListBuilder<GCheckoutLineInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCollectionData_products_edges)]), () => new ListBuilder<GCollectionData_products_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCollectionData_products_edges_node_images)]), () => new ListBuilder<GCollectionData_products_edges_node_images>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GCollectionsData_collections_edges)]), () => new ListBuilder<GCollectionsData_collections_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GConfigurationItemInput)]), () => new ListBuilder<GConfigurationItemInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GDiscountStatusEnum)]), () => new ListBuilder<GDiscountStatusEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GDiscountStatusEnum)]), () => new ListBuilder<GDiscountStatusEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GVoucherDiscountType)]), () => new ListBuilder<GVoucherDiscountType>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GFeaturedProductsData_shop_homepageCollection_products_edges)]), () => new ListBuilder<GFeaturedProductsData_shop_homepageCollection_products_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GMenuItemInput)]), () => new ListBuilder<GMenuItemInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GOrderFulfillLineInput)]), () => new ListBuilder<GOrderFulfillLineInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GOrderFulfillStockInput)]), () => new ListBuilder<GOrderFulfillStockInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GOrderLineCreateInput)]), () => new ListBuilder<GOrderLineCreateInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GPaymentChargeStatusEnum)]), () => new ListBuilder<GPaymentChargeStatusEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GOrderStatusFilter)]), () => new ListBuilder<GOrderStatusFilter>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GPermissionEnum)]), () => new ListBuilder<GPermissionEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GPermissionEnum)]), () => new ListBuilder<GPermissionEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GPermissionEnum)]), () => new ListBuilder<GPermissionEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GPermissionEnum)]), () => new ListBuilder<GPermissionEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GPermissionEnum)]), () => new ListBuilder<GPermissionEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_attributes_values)]), () => new ListBuilder<GProductDetailsData_product_attributes_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_category_products_edges)]), () => new ListBuilder<GProductDetailsData_product_category_products_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_images)]), () => new ListBuilder<GProductDetailsData_product_images>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_attributes)]), () => new ListBuilder<GProductDetailsData_product_attributes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_variants)]), () => new ListBuilder<GProductDetailsData_product_variants>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_variants_attributes_values)]), () => new ListBuilder<GProductDetailsData_product_variants_attributes_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_variants_images)]), () => new ListBuilder<GProductDetailsData_product_variants_images>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductDetailsData_product_variants_attributes)]), () => new ListBuilder<GProductDetailsData_product_variants_attributes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductVariantFieldsData_attributes_values)]), () => new ListBuilder<GProductVariantFieldsData_attributes_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductVariantFieldsData_images)]), () => new ListBuilder<GProductVariantFieldsData_images>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GProductVariantFieldsData_attributes)]), () => new ListBuilder<GProductVariantFieldsData_attributes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GSearchProductsData_products_edges)]), () => new ListBuilder<GSearchProductsData_products_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GSelectedAttributeFieldsData_values)]), () => new ListBuilder<GSelectedAttributeFieldsData_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GVariantListData_productVariants_edges)]), () => new ListBuilder<GVariantListData_productVariants_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GVariantListData_productVariants_edges_node_attributes_values)]), () => new ListBuilder<GVariantListData_productVariants_edges_node_attributes_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GVariantListData_productVariants_edges_node_images)]), () => new ListBuilder<GVariantListData_productVariants_edges_node_images>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GVariantListData_productVariants_edges_node_attributes)]), () => new ListBuilder<GVariantListData_productVariants_edges_node_attributes>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GWebhookEventTypeEnum)]), () => new ListBuilder<GWebhookEventTypeEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GWebhookEventTypeEnum)]), () => new ListBuilder<GWebhookEventTypeEnum>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GattributesData_attributes_edges)]), () => new ListBuilder<GattributesData_attributes_edges>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GattributesData_attributes_edges_node_values)]), () => new ListBuilder<GattributesData_attributes_edges_node_values>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeValueCreateInput)]), () => new ListBuilder<GAttributeValueCreateInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(GAttributeInput)]), () => new ListBuilder<GAttributeInput>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>())
      ..addBuilderFactory(const FullType(BuiltList, const [const FullType(String)]), () => new ListBuilder<String>()))
    .build();

// ignore_for_file: always_put_control_body_on_new_line,always_specify_types,annotate_overrides,avoid_annotating_with_dynamic,avoid_as,avoid_catches_without_on_clauses,avoid_returning_this,lines_longer_than_80_chars,omit_local_variable_types,prefer_expression_function_bodies,sort_constructors_first,test_types_in_equals,unnecessary_const,unnecessary_new
