import 'package:built_collection/built_collection.dart';
import 'package:built_value/serializer.dart';
import 'package:built_value/standard_json_plugin.dart' show StandardJsonPlugin;
import 'package:gql_code_builder/src/serializers/operation_serializer.dart'
    show OperationSerializer;
import 'package:ispot/app/data/provider/account/graphql/change_password/change_password.data.gql.dart'
    show
        GchangePasswordData,
        GchangePasswordData_passwordChange,
        GchangePasswordData_passwordChange_accountErrors,
        GchangePasswordData_passwordChange_user;
import 'package:ispot/app/data/provider/account/graphql/change_password/change_password.req.gql.dart'
    show GchangePasswordReq;
import 'package:ispot/app/data/provider/account/graphql/change_password/change_password.var.gql.dart'
    show GchangePasswordVars;
import 'package:ispot/app/data/provider/account/graphql/update_basic_details/update_details.data.gql.dart'
    show
        GupdateBasicDetailsData,
        GupdateBasicDetailsData_accountUpdate,
        GupdateBasicDetailsData_accountUpdate_accountErrors,
        GupdateBasicDetailsData_accountUpdate_user;
import 'package:ispot/app/data/provider/account/graphql/update_basic_details/update_details.req.gql.dart'
    show GupdateBasicDetailsReq;
import 'package:ispot/app/data/provider/account/graphql/update_basic_details/update_details.var.gql.dart'
    show GupdateBasicDetailsVars;
import 'package:ispot/app/data/provider/account/graphql/user/user.data.gql.dart'
    show
        GMeData,
        GMeData_me,
        GMeData_me_addresses,
        GMeData_me_addresses_country;
import 'package:ispot/app/data/provider/account/graphql/user/user.req.gql.dart'
    show GMeReq;
import 'package:ispot/app/data/provider/account/graphql/user/user.var.gql.dart'
    show GMeVars;
import 'package:ispot/app/data/provider/address/graphql/address/create_address/create_address.data.gql.dart'
    show
        GaccountAddressCreateData,
        GaccountAddressCreateData_accountAddressCreate,
        GaccountAddressCreateData_accountAddressCreate_accountErrors,
        GaccountAddressCreateData_accountAddressCreate_user,
        GaccountAddressCreateData_accountAddressCreate_user_addresses,
        GaccountAddressCreateData_accountAddressCreate_user_addresses_country;
import 'package:ispot/app/data/provider/address/graphql/address/create_address/create_address.req.gql.dart'
    show GaccountAddressCreateReq;
import 'package:ispot/app/data/provider/address/graphql/address/create_address/create_address.var.gql.dart'
    show GaccountAddressCreateVars;
import 'package:ispot/app/data/provider/address/graphql/address/delete_address/delete_address.data.gql.dart'
    show
        GaddressDeleteData,
        GaddressDeleteData_accountAddressDelete,
        GaddressDeleteData_accountAddressDelete_accountErrors,
        GaddressDeleteData_accountAddressDelete_user,
        GaddressDeleteData_accountAddressDelete_user_addresses,
        GaddressDeleteData_accountAddressDelete_user_addresses_country;
import 'package:ispot/app/data/provider/address/graphql/address/delete_address/delete_address.req.gql.dart'
    show GaddressDeleteReq;
import 'package:ispot/app/data/provider/address/graphql/address/delete_address/delete_address.var.gql.dart'
    show GaddressDeleteVars;
import 'package:ispot/app/data/provider/address/graphql/address/get_addresses/get_addresses.data.gql.dart'
    show
        GgetAddressesData,
        GgetAddressesData_me,
        GgetAddressesData_me_addresses,
        GgetAddressesData_me_addresses_country;
import 'package:ispot/app/data/provider/address/graphql/address/get_addresses/get_addresses.req.gql.dart'
    show GgetAddressesReq;
import 'package:ispot/app/data/provider/address/graphql/address/get_addresses/get_addresses.var.gql.dart'
    show GgetAddressesVars;
import 'package:ispot/app/data/provider/address/graphql/address/update_address/address_update.data.gql.dart'
    show
        GaddressUpdateData,
        GaddressUpdateData_accountAddressUpdate,
        GaddressUpdateData_accountAddressUpdate_accountErrors,
        GaddressUpdateData_accountAddressUpdate_user,
        GaddressUpdateData_accountAddressUpdate_user_addresses,
        GaddressUpdateData_accountAddressUpdate_user_addresses_country;
import 'package:ispot/app/data/provider/address/graphql/address/update_address/address_update.req.gql.dart'
    show GaddressUpdateReq;
import 'package:ispot/app/data/provider/address/graphql/address/update_address/address_update.var.gql.dart'
    show GaddressUpdateVars;
import 'package:ispot/app/data/provider/attribute/graphql/attributes.data.gql.dart'
    show
        GattributesData,
        GattributesData_attributes,
        GattributesData_attributes_edges,
        GattributesData_attributes_edges_node,
        GattributesData_attributes_edges_node_values,
        GattributesData_attributes_pageInfo;
import 'package:ispot/app/data/provider/attribute/graphql/attributes.req.gql.dart'
    show GattributesReq;
import 'package:ispot/app/data/provider/attribute/graphql/attributes.var.gql.dart'
    show GattributesVars;
import 'package:ispot/app/data/provider/auth/graphql/forgot_password/forgotPassword.data.gql.dart'
    show
        GrequestPasswordResetData,
        GrequestPasswordResetData_requestPasswordReset,
        GrequestPasswordResetData_requestPasswordReset_accountErrors;
import 'package:ispot/app/data/provider/auth/graphql/forgot_password/forgotPassword.req.gql.dart'
    show GrequestPasswordResetReq;
import 'package:ispot/app/data/provider/auth/graphql/forgot_password/forgotPassword.var.gql.dart'
    show GrequestPasswordResetVars;
import 'package:ispot/app/data/provider/auth/graphql/login/login.data.gql.dart'
    show
        GtokenCreateData,
        GtokenCreateData_tokenCreate,
        GtokenCreateData_tokenCreate_accountErrors,
        GtokenCreateData_tokenCreate_user;
import 'package:ispot/app/data/provider/auth/graphql/login/login.req.gql.dart'
    show GtokenCreateReq;
import 'package:ispot/app/data/provider/auth/graphql/login/login.var.gql.dart'
    show GtokenCreateVars;
import 'package:ispot/app/data/provider/auth/graphql/register/create_account.data.gql.dart'
    show
        GregisterAccountData,
        GregisterAccountData_accountRegister,
        GregisterAccountData_accountRegister_accountErrors,
        GregisterAccountData_accountRegister_user;
import 'package:ispot/app/data/provider/auth/graphql/register/create_account.req.gql.dart'
    show GregisterAccountReq;
import 'package:ispot/app/data/provider/auth/graphql/register/create_account.var.gql.dart'
    show GregisterAccountVars;
import 'package:ispot/app/data/provider/categories/graphql/drawer_category/drawer_categories.data.gql.dart'
    show
        GDrawerCategoriesData,
        GDrawerCategoriesData_categories,
        GDrawerCategoriesData_categories_edges,
        GDrawerCategoriesData_categories_edges_node,
        GDrawerCategoriesData_categories_edges_node_children,
        GDrawerCategoriesData_categories_edges_node_children_edges,
        GDrawerCategoriesData_categories_edges_node_children_edges_node;
import 'package:ispot/app/data/provider/categories/graphql/drawer_category/drawer_categories.req.gql.dart'
    show GDrawerCategoriesReq;
import 'package:ispot/app/data/provider/categories/graphql/drawer_category/drawer_categories.var.gql.dart'
    show GDrawerCategoriesVars;
import 'package:ispot/app/data/provider/categories/graphql/home_category/categories.data.gql.dart'
    show
        GCategoryListData,
        GCategoryListData_categories,
        GCategoryListData_categories_edges,
        GCategoryListData_categories_edges_node,
        GCategoryListData_categories_edges_node_backgroundImage,
        GCategoryListData_categories_pageInfo;
import 'package:ispot/app/data/provider/categories/graphql/home_category/categories.req.gql.dart'
    show GCategoryListReq;
import 'package:ispot/app/data/provider/categories/graphql/home_category/categories.var.gql.dart'
    show GCategoryListVars;
import 'package:ispot/app/data/provider/category/graphql/category.data.gql.dart'
    show
        GCategoryData,
        GCategoryData_attributes,
        GCategoryData_attributes_edges,
        GCategoryData_attributes_edges_node,
        GCategoryData_attributes_edges_node_values,
        GCategoryData_category,
        GCategoryData_category_ancestors,
        GCategoryData_category_ancestors_edges,
        GCategoryData_category_ancestors_edges_node,
        GCategoryData_category_backgroundImage,
        GCategoryData_products,
        GCategoryData_products_edges,
        GCategoryData_products_edges_node,
        GCategoryData_products_edges_node_images,
        GCategoryData_products_edges_node_pricing,
        GCategoryData_products_edges_node_pricing_priceRange,
        GCategoryData_products_edges_node_pricing_priceRange_start,
        GCategoryData_products_edges_node_pricing_priceRange_start_net,
        GCategoryData_products_edges_node_pricing_priceRange_stop,
        GCategoryData_products_edges_node_pricing_priceRange_stop_net,
        GCategoryData_products_edges_node_thumbnail,
        GCategoryData_products_pageInfo;
import 'package:ispot/app/data/provider/category/graphql/category.req.gql.dart'
    show GCategoryReq;
import 'package:ispot/app/data/provider/category/graphql/category.var.gql.dart'
    show GCategoryVars;
import 'package:ispot/app/data/provider/checkout/checkout_create/checkout_create.data.gql.dart'
    show
        GcreateCheckoutData,
        GcreateCheckoutData_checkoutCreate,
        GcreateCheckoutData_checkoutCreate_checkout,
        GcreateCheckoutData_checkoutCreate_checkoutErrors,
        GcreateCheckoutData_checkoutCreate_checkout_availablePaymentGateways,
        GcreateCheckoutData_checkoutCreate_checkout_availablePaymentGateways_config,
        GcreateCheckoutData_checkoutCreate_checkout_availableShippingMethods,
        GcreateCheckoutData_checkoutCreate_checkout_totalPrice,
        GcreateCheckoutData_checkoutCreate_checkout_totalPrice_gross;
import 'package:ispot/app/data/provider/checkout/checkout_create/checkout_create.req.gql.dart'
    show GcreateCheckoutReq;
import 'package:ispot/app/data/provider/checkout/checkout_create/checkout_create.var.gql.dart'
    show GcreateCheckoutVars;
import 'package:ispot/app/data/provider/collection/graphql/collection.data.gql.dart'
    show
        GCollectionData,
        GCollectionData_collection,
        GCollectionData_collection_backgroundImage,
        GCollectionData_products,
        GCollectionData_products_edges,
        GCollectionData_products_edges_node,
        GCollectionData_products_edges_node_images,
        GCollectionData_products_edges_node_pricing,
        GCollectionData_products_edges_node_pricing_priceRange,
        GCollectionData_products_edges_node_pricing_priceRange_start,
        GCollectionData_products_edges_node_pricing_priceRange_start_net,
        GCollectionData_products_edges_node_pricing_priceRange_stop,
        GCollectionData_products_edges_node_pricing_priceRange_stop_net,
        GCollectionData_products_edges_node_thumbnail,
        GCollectionData_products_pageInfo;
import 'package:ispot/app/data/provider/collection/graphql/collection.req.gql.dart'
    show GCollectionReq;
import 'package:ispot/app/data/provider/collection/graphql/collection.var.gql.dart'
    show GCollectionVars;
import 'package:ispot/app/data/provider/collections/graphql/collections.data.gql.dart'
    show
        GCollectionsData,
        GCollectionsData_collections,
        GCollectionsData_collections_edges,
        GCollectionsData_collections_edges_node,
        GCollectionsData_collections_edges_node_backgroundImage,
        GCollectionsData_collections_pageInfo;
import 'package:ispot/app/data/provider/collections/graphql/collections.req.gql.dart'
    show GCollectionsReq;
import 'package:ispot/app/data/provider/collections/graphql/collections.var.gql.dart'
    show GCollectionsVars;
import 'package:ispot/app/data/provider/home/graphql/home/products/featured_products.data.gql.dart'
    show
        GFeaturedProductsData,
        GFeaturedProductsData_shop,
        GFeaturedProductsData_shop_homepageCollection,
        GFeaturedProductsData_shop_homepageCollection_backgroundImage,
        GFeaturedProductsData_shop_homepageCollection_products,
        GFeaturedProductsData_shop_homepageCollection_products_edges,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_category,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_start,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_start_net,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_stop,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_stop_net,
        GFeaturedProductsData_shop_homepageCollection_products_edges_node_thumbnail;
import 'package:ispot/app/data/provider/home/graphql/home/products/featured_products.req.gql.dart'
    show GFeaturedProductsReq;
import 'package:ispot/app/data/provider/home/graphql/home/products/featured_products.var.gql.dart'
    show GFeaturedProductsVars;
import 'package:ispot/app/data/provider/orders/graphql/orders.data.gql.dart'
    show
        GOrdersData,
        GOrdersData_me,
        GOrdersData_me_orders,
        GOrdersData_me_orders_edges,
        GOrdersData_me_orders_edges_node,
        GOrdersData_me_orders_edges_node_lines,
        GOrdersData_me_orders_edges_node_total,
        GOrdersData_me_orders_edges_node_total_gross,
        GOrdersData_me_orders_edges_node_total_net,
        GOrdersData_me_orders_pageInfo;
import 'package:ispot/app/data/provider/orders/graphql/orders.req.gql.dart'
    show GOrdersReq;
import 'package:ispot/app/data/provider/orders/graphql/orders.var.gql.dart'
    show GOrdersVars;
import 'package:ispot/app/data/provider/product/graphql/product.data.gql.dart'
    show
        GBasicProductFieldsData,
        GBasicProductFieldsData_thumbnail,
        GPriceData,
        GPriceData_net,
        GProductDetailsData,
        GProductDetailsData_product,
        GProductDetailsData_product_attributes,
        GProductDetailsData_product_attributes_attribute,
        GProductDetailsData_product_attributes_values,
        GProductDetailsData_product_category,
        GProductDetailsData_product_category_products,
        GProductDetailsData_product_category_products_edges,
        GProductDetailsData_product_category_products_edges_node,
        GProductDetailsData_product_category_products_edges_node_pricing,
        GProductDetailsData_product_category_products_edges_node_pricing_priceRange,
        GProductDetailsData_product_category_products_edges_node_pricing_priceRange_start,
        GProductDetailsData_product_category_products_edges_node_pricing_priceRange_start_net,
        GProductDetailsData_product_category_products_edges_node_pricing_priceRange_stop,
        GProductDetailsData_product_category_products_edges_node_pricing_priceRange_stop_net,
        GProductDetailsData_product_category_products_edges_node_thumbnail,
        GProductDetailsData_product_images,
        GProductDetailsData_product_pricing,
        GProductDetailsData_product_pricing_priceRange,
        GProductDetailsData_product_pricing_priceRange_start,
        GProductDetailsData_product_pricing_priceRange_start_net,
        GProductDetailsData_product_pricing_priceRange_stop,
        GProductDetailsData_product_pricing_priceRange_stop_net,
        GProductDetailsData_product_thumbnail,
        GProductDetailsData_product_variants,
        GProductDetailsData_product_variants_attributes,
        GProductDetailsData_product_variants_attributes_attribute,
        GProductDetailsData_product_variants_attributes_values,
        GProductDetailsData_product_variants_images,
        GProductDetailsData_product_variants_pricing,
        GProductDetailsData_product_variants_pricing_price,
        GProductDetailsData_product_variants_pricing_priceUndiscounted,
        GProductDetailsData_product_variants_pricing_priceUndiscounted_net,
        GProductDetailsData_product_variants_pricing_price_net,
        GProductPricingFieldData,
        GProductPricingFieldData_pricing,
        GProductPricingFieldData_pricing_priceRange,
        GProductPricingFieldData_pricing_priceRange_start,
        GProductPricingFieldData_pricing_priceRange_start_net,
        GProductPricingFieldData_pricing_priceRange_stop,
        GProductPricingFieldData_pricing_priceRange_stop_net,
        GProductVariantFieldsData,
        GProductVariantFieldsData_attributes,
        GProductVariantFieldsData_attributes_attribute,
        GProductVariantFieldsData_attributes_values,
        GProductVariantFieldsData_images,
        GProductVariantFieldsData_pricing,
        GProductVariantFieldsData_pricing_price,
        GProductVariantFieldsData_pricing_priceUndiscounted,
        GProductVariantFieldsData_pricing_priceUndiscounted_net,
        GProductVariantFieldsData_pricing_price_net,
        GSelectedAttributeFieldsData,
        GSelectedAttributeFieldsData_attribute,
        GSelectedAttributeFieldsData_values,
        GVariantListData,
        GVariantListData_productVariants,
        GVariantListData_productVariants_edges,
        GVariantListData_productVariants_edges_node,
        GVariantListData_productVariants_edges_node_attributes,
        GVariantListData_productVariants_edges_node_attributes_attribute,
        GVariantListData_productVariants_edges_node_attributes_values,
        GVariantListData_productVariants_edges_node_images,
        GVariantListData_productVariants_edges_node_pricing,
        GVariantListData_productVariants_edges_node_pricing_price,
        GVariantListData_productVariants_edges_node_pricing_priceUndiscounted,
        GVariantListData_productVariants_edges_node_pricing_priceUndiscounted_net,
        GVariantListData_productVariants_edges_node_pricing_price_net,
        GVariantListData_productVariants_edges_node_product,
        GVariantListData_productVariants_edges_node_product_thumbnail;
import 'package:ispot/app/data/provider/product/graphql/product.req.gql.dart'
    show
        GBasicProductFieldsReq,
        GPriceReq,
        GProductDetailsReq,
        GProductPricingFieldReq,
        GProductVariantFieldsReq,
        GSelectedAttributeFieldsReq,
        GVariantListReq;
import 'package:ispot/app/data/provider/product/graphql/product.var.gql.dart'
    show
        GBasicProductFieldsVars,
        GPriceVars,
        GProductDetailsVars,
        GProductPricingFieldVars,
        GProductVariantFieldsVars,
        GSelectedAttributeFieldsVars,
        GVariantListVars;
import 'package:ispot/app/data/provider/search/graphql/search.data.gql.dart'
    show
        GSearchProductsData,
        GSearchProductsData_products,
        GSearchProductsData_products_edges,
        GSearchProductsData_products_edges_node,
        GSearchProductsData_products_edges_node_pricing,
        GSearchProductsData_products_edges_node_pricing_priceRange,
        GSearchProductsData_products_edges_node_pricing_priceRange_start,
        GSearchProductsData_products_edges_node_pricing_priceRange_start_net,
        GSearchProductsData_products_edges_node_pricing_priceRange_stop,
        GSearchProductsData_products_edges_node_pricing_priceRange_stop_net,
        GSearchProductsData_products_edges_node_thumbnail,
        GSearchProductsData_products_edges_node_thumbnail2x,
        GSearchProductsData_products_pageInfo;
import 'package:ispot/app/data/provider/search/graphql/search.req.gql.dart'
    show GSearchProductsReq;
import 'package:ispot/app/data/provider/search/graphql/search.var.gql.dart'
    show GSearchProductsVars;
import 'package:ispot/graphql/schema.schema.gql.dart'
    show
        GAccountErrorCode,
        GAccountInput,
        GAccountRegisterInput,
        GAddressInput,
        GAddressTypeEnum,
        GAppErrorCode,
        GAppFilterInput,
        GAppInput,
        GAppSortField,
        GAppSortingInput,
        GAppTokenInput,
        GAttributeAssignInput,
        GAttributeCreateInput,
        GAttributeFilterInput,
        GAttributeInput,
        GAttributeInputTypeEnum,
        GAttributeSortField,
        GAttributeSortingInput,
        GAttributeTypeEnum,
        GAttributeUpdateInput,
        GAttributeValueCreateInput,
        GAttributeValueInput,
        GAttributeValueType,
        GAuthorizationKeyInput,
        GAuthorizationKeyType,
        GCatalogueInput,
        GCategoryFilterInput,
        GCategoryInput,
        GCategorySortField,
        GCategorySortingInput,
        GCheckoutCreateInput,
        GCheckoutErrorCode,
        GCheckoutLineInput,
        GCollectionCreateInput,
        GCollectionFilterInput,
        GCollectionInput,
        GCollectionPublished,
        GCollectionSortField,
        GCollectionSortingInput,
        GConfigurationItemInput,
        GConfigurationTypeFieldEnum,
        GCountryCode,
        GCustomerEventsEnum,
        GCustomerFilterInput,
        GCustomerInput,
        GDate,
        GDateRangeInput,
        GDateTime,
        GDateTimeRangeInput,
        GDecimal,
        GDigitalContentInput,
        GDigitalContentUploadInput,
        GDigitalContentUrlCreateInput,
        GDiscountErrorCode,
        GDiscountStatusEnum,
        GDiscountValueTypeEnum,
        GDraftOrderCreateInput,
        GDraftOrderInput,
        GFulfillmentCancelInput,
        GFulfillmentStatus,
        GFulfillmentUpdateTrackingInput,
        GGenericScalar,
        GGiftCardCreateInput,
        GGiftCardErrorCode,
        GGiftCardUpdateInput,
        GIntRangeInput,
        GJSONString,
        GLanguageCodeEnum,
        GMenuCreateInput,
        GMenuErrorCode,
        GMenuFilterInput,
        GMenuInput,
        GMenuItemCreateInput,
        GMenuItemFilterInput,
        GMenuItemInput,
        GMenuItemMoveInput,
        GMenuItemSortingInput,
        GMenuItemsSortField,
        GMenuSortField,
        GMenuSortingInput,
        GMetaInput,
        GMetaPath,
        GMetadataErrorCode,
        GMetadataInput,
        GMoveProductInput,
        GNameTranslationInput,
        GNavigationType,
        GOrderAction,
        GOrderAddNoteInput,
        GOrderDirection,
        GOrderDraftFilterInput,
        GOrderErrorCode,
        GOrderEventsEmailsEnum,
        GOrderEventsEnum,
        GOrderFilterInput,
        GOrderFulfillInput,
        GOrderFulfillLineInput,
        GOrderFulfillStockInput,
        GOrderLineCreateInput,
        GOrderLineInput,
        GOrderSortField,
        GOrderSortingInput,
        GOrderStatus,
        GOrderStatusFilter,
        GOrderUpdateInput,
        GOrderUpdateShippingInput,
        GPageErrorCode,
        GPageFilterInput,
        GPageInput,
        GPageSortField,
        GPageSortingInput,
        GPageTranslationInput,
        GPaymentChargeStatusEnum,
        GPaymentErrorCode,
        GPaymentInput,
        GPermissionEnum,
        GPermissionGroupCreateInput,
        GPermissionGroupErrorCode,
        GPermissionGroupFilterInput,
        GPermissionGroupSortField,
        GPermissionGroupSortingInput,
        GPermissionGroupUpdateInput,
        GPluginErrorCode,
        GPluginFilterInput,
        GPluginSortField,
        GPluginSortingInput,
        GPluginUpdateInput,
        GPriceRangeInput,
        GProductCreateInput,
        GProductErrorCode,
        GProductFilterInput,
        GProductImageCreateInput,
        GProductImageUpdateInput,
        GProductInput,
        GProductOrder,
        GProductOrderField,
        GProductStockFilterInput,
        GProductTypeConfigurable,
        GProductTypeEnum,
        GProductTypeFilterInput,
        GProductTypeInput,
        GProductTypeSortField,
        GProductTypeSortingInput,
        GProductVariantBulkCreateInput,
        GProductVariantCreateInput,
        GProductVariantInput,
        GReorderInput,
        GReportingPeriod,
        GSaleFilterInput,
        GSaleInput,
        GSaleSortField,
        GSaleSortingInput,
        GSaleType,
        GSeoInput,
        GServiceAccountFilterInput,
        GServiceAccountInput,
        GServiceAccountSortField,
        GServiceAccountSortingInput,
        GServiceAccountTokenInput,
        GShippingErrorCode,
        GShippingMethodTypeEnum,
        GShippingPriceInput,
        GShippingZoneCreateInput,
        GShippingZoneUpdateInput,
        GShopErrorCode,
        GShopSettingsInput,
        GShopSettingsTranslationInput,
        GSiteDomainInput,
        GStaffCreateInput,
        GStaffMemberStatus,
        GStaffNotificationRecipientInput,
        GStaffUpdateInput,
        GStaffUserInput,
        GStockAvailability,
        GStockErrorCode,
        GStockFilterInput,
        GStockInput,
        GTaxRateType,
        GTransactionError,
        GTransactionKind,
        GTranslatableKinds,
        GTranslationErrorCode,
        GTranslationInput,
        GUUID,
        GUpload,
        GUserCreateInput,
        GUserSortField,
        GUserSortingInput,
        GVoucherDiscountType,
        GVoucherFilterInput,
        GVoucherInput,
        GVoucherSortField,
        GVoucherSortingInput,
        GVoucherTypeEnum,
        GWarehouseAddressInput,
        GWarehouseCreateInput,
        GWarehouseErrorCode,
        GWarehouseFilterInput,
        GWarehouseSortField,
        GWarehouseSortingInput,
        GWarehouseUpdateInput,
        GWebhookCreateInput,
        GWebhookErrorCode,
        GWebhookEventTypeEnum,
        GWebhookFilterInput,
        GWebhookSampleEventTypeEnum,
        GWebhookSortField,
        GWebhookSortingInput,
        GWebhookUpdateInput,
        GWeightScalar,
        GWeightUnitsEnum,
        G_Any;

part 'serializers.gql.g.dart';

final SerializersBuilder _serializersBuilder = _$serializers.toBuilder()
  ..add(OperationSerializer())
  ..addPlugin(StandardJsonPlugin());
@SerializersFor([
  GAccountErrorCode,
  GAccountInput,
  GAccountRegisterInput,
  GAddressInput,
  GAddressTypeEnum,
  GAppErrorCode,
  GAppFilterInput,
  GAppInput,
  GAppSortField,
  GAppSortingInput,
  GAppTokenInput,
  GAttributeAssignInput,
  GAttributeCreateInput,
  GAttributeFilterInput,
  GAttributeInput,
  GAttributeInputTypeEnum,
  GAttributeSortField,
  GAttributeSortingInput,
  GAttributeTypeEnum,
  GAttributeUpdateInput,
  GAttributeValueCreateInput,
  GAttributeValueInput,
  GAttributeValueType,
  GAuthorizationKeyInput,
  GAuthorizationKeyType,
  GBasicProductFieldsData,
  GBasicProductFieldsData_thumbnail,
  GBasicProductFieldsReq,
  GBasicProductFieldsVars,
  GCatalogueInput,
  GCategoryData,
  GCategoryData_attributes,
  GCategoryData_attributes_edges,
  GCategoryData_attributes_edges_node,
  GCategoryData_attributes_edges_node_values,
  GCategoryData_category,
  GCategoryData_category_ancestors,
  GCategoryData_category_ancestors_edges,
  GCategoryData_category_ancestors_edges_node,
  GCategoryData_category_backgroundImage,
  GCategoryData_products,
  GCategoryData_products_edges,
  GCategoryData_products_edges_node,
  GCategoryData_products_edges_node_images,
  GCategoryData_products_edges_node_pricing,
  GCategoryData_products_edges_node_pricing_priceRange,
  GCategoryData_products_edges_node_pricing_priceRange_start,
  GCategoryData_products_edges_node_pricing_priceRange_start_net,
  GCategoryData_products_edges_node_pricing_priceRange_stop,
  GCategoryData_products_edges_node_pricing_priceRange_stop_net,
  GCategoryData_products_edges_node_thumbnail,
  GCategoryData_products_pageInfo,
  GCategoryFilterInput,
  GCategoryInput,
  GCategoryListData,
  GCategoryListData_categories,
  GCategoryListData_categories_edges,
  GCategoryListData_categories_edges_node,
  GCategoryListData_categories_edges_node_backgroundImage,
  GCategoryListData_categories_pageInfo,
  GCategoryListReq,
  GCategoryListVars,
  GCategoryReq,
  GCategorySortField,
  GCategorySortingInput,
  GCategoryVars,
  GCheckoutCreateInput,
  GCheckoutErrorCode,
  GCheckoutLineInput,
  GCollectionCreateInput,
  GCollectionData,
  GCollectionData_collection,
  GCollectionData_collection_backgroundImage,
  GCollectionData_products,
  GCollectionData_products_edges,
  GCollectionData_products_edges_node,
  GCollectionData_products_edges_node_images,
  GCollectionData_products_edges_node_pricing,
  GCollectionData_products_edges_node_pricing_priceRange,
  GCollectionData_products_edges_node_pricing_priceRange_start,
  GCollectionData_products_edges_node_pricing_priceRange_start_net,
  GCollectionData_products_edges_node_pricing_priceRange_stop,
  GCollectionData_products_edges_node_pricing_priceRange_stop_net,
  GCollectionData_products_edges_node_thumbnail,
  GCollectionData_products_pageInfo,
  GCollectionFilterInput,
  GCollectionInput,
  GCollectionPublished,
  GCollectionReq,
  GCollectionSortField,
  GCollectionSortingInput,
  GCollectionVars,
  GCollectionsData,
  GCollectionsData_collections,
  GCollectionsData_collections_edges,
  GCollectionsData_collections_edges_node,
  GCollectionsData_collections_edges_node_backgroundImage,
  GCollectionsData_collections_pageInfo,
  GCollectionsReq,
  GCollectionsVars,
  GConfigurationItemInput,
  GConfigurationTypeFieldEnum,
  GCountryCode,
  GCustomerEventsEnum,
  GCustomerFilterInput,
  GCustomerInput,
  GDate,
  GDateRangeInput,
  GDateTime,
  GDateTimeRangeInput,
  GDecimal,
  GDigitalContentInput,
  GDigitalContentUploadInput,
  GDigitalContentUrlCreateInput,
  GDiscountErrorCode,
  GDiscountStatusEnum,
  GDiscountValueTypeEnum,
  GDraftOrderCreateInput,
  GDraftOrderInput,
  GDrawerCategoriesData,
  GDrawerCategoriesData_categories,
  GDrawerCategoriesData_categories_edges,
  GDrawerCategoriesData_categories_edges_node,
  GDrawerCategoriesData_categories_edges_node_children,
  GDrawerCategoriesData_categories_edges_node_children_edges,
  GDrawerCategoriesData_categories_edges_node_children_edges_node,
  GDrawerCategoriesReq,
  GDrawerCategoriesVars,
  GFeaturedProductsData,
  GFeaturedProductsData_shop,
  GFeaturedProductsData_shop_homepageCollection,
  GFeaturedProductsData_shop_homepageCollection_backgroundImage,
  GFeaturedProductsData_shop_homepageCollection_products,
  GFeaturedProductsData_shop_homepageCollection_products_edges,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_category,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_start,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_start_net,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_stop,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_pricing_priceRange_stop_net,
  GFeaturedProductsData_shop_homepageCollection_products_edges_node_thumbnail,
  GFeaturedProductsReq,
  GFeaturedProductsVars,
  GFulfillmentCancelInput,
  GFulfillmentStatus,
  GFulfillmentUpdateTrackingInput,
  GGenericScalar,
  GGiftCardCreateInput,
  GGiftCardErrorCode,
  GGiftCardUpdateInput,
  GIntRangeInput,
  GJSONString,
  GLanguageCodeEnum,
  GMeData,
  GMeData_me,
  GMeData_me_addresses,
  GMeData_me_addresses_country,
  GMeReq,
  GMeVars,
  GMenuCreateInput,
  GMenuErrorCode,
  GMenuFilterInput,
  GMenuInput,
  GMenuItemCreateInput,
  GMenuItemFilterInput,
  GMenuItemInput,
  GMenuItemMoveInput,
  GMenuItemSortingInput,
  GMenuItemsSortField,
  GMenuSortField,
  GMenuSortingInput,
  GMetaInput,
  GMetaPath,
  GMetadataErrorCode,
  GMetadataInput,
  GMoveProductInput,
  GNameTranslationInput,
  GNavigationType,
  GOrderAction,
  GOrderAddNoteInput,
  GOrderDirection,
  GOrderDraftFilterInput,
  GOrderErrorCode,
  GOrderEventsEmailsEnum,
  GOrderEventsEnum,
  GOrderFilterInput,
  GOrderFulfillInput,
  GOrderFulfillLineInput,
  GOrderFulfillStockInput,
  GOrderLineCreateInput,
  GOrderLineInput,
  GOrderSortField,
  GOrderSortingInput,
  GOrderStatus,
  GOrderStatusFilter,
  GOrderUpdateInput,
  GOrderUpdateShippingInput,
  GOrdersData,
  GOrdersData_me,
  GOrdersData_me_orders,
  GOrdersData_me_orders_edges,
  GOrdersData_me_orders_edges_node,
  GOrdersData_me_orders_edges_node_lines,
  GOrdersData_me_orders_edges_node_total,
  GOrdersData_me_orders_edges_node_total_gross,
  GOrdersData_me_orders_edges_node_total_net,
  GOrdersData_me_orders_pageInfo,
  GOrdersReq,
  GOrdersVars,
  GPageErrorCode,
  GPageFilterInput,
  GPageInput,
  GPageSortField,
  GPageSortingInput,
  GPageTranslationInput,
  GPaymentChargeStatusEnum,
  GPaymentErrorCode,
  GPaymentInput,
  GPermissionEnum,
  GPermissionGroupCreateInput,
  GPermissionGroupErrorCode,
  GPermissionGroupFilterInput,
  GPermissionGroupSortField,
  GPermissionGroupSortingInput,
  GPermissionGroupUpdateInput,
  GPluginErrorCode,
  GPluginFilterInput,
  GPluginSortField,
  GPluginSortingInput,
  GPluginUpdateInput,
  GPriceData,
  GPriceData_net,
  GPriceRangeInput,
  GPriceReq,
  GPriceVars,
  GProductCreateInput,
  GProductDetailsData,
  GProductDetailsData_product,
  GProductDetailsData_product_attributes,
  GProductDetailsData_product_attributes_attribute,
  GProductDetailsData_product_attributes_values,
  GProductDetailsData_product_category,
  GProductDetailsData_product_category_products,
  GProductDetailsData_product_category_products_edges,
  GProductDetailsData_product_category_products_edges_node,
  GProductDetailsData_product_category_products_edges_node_pricing,
  GProductDetailsData_product_category_products_edges_node_pricing_priceRange,
  GProductDetailsData_product_category_products_edges_node_pricing_priceRange_start,
  GProductDetailsData_product_category_products_edges_node_pricing_priceRange_start_net,
  GProductDetailsData_product_category_products_edges_node_pricing_priceRange_stop,
  GProductDetailsData_product_category_products_edges_node_pricing_priceRange_stop_net,
  GProductDetailsData_product_category_products_edges_node_thumbnail,
  GProductDetailsData_product_images,
  GProductDetailsData_product_pricing,
  GProductDetailsData_product_pricing_priceRange,
  GProductDetailsData_product_pricing_priceRange_start,
  GProductDetailsData_product_pricing_priceRange_start_net,
  GProductDetailsData_product_pricing_priceRange_stop,
  GProductDetailsData_product_pricing_priceRange_stop_net,
  GProductDetailsData_product_thumbnail,
  GProductDetailsData_product_variants,
  GProductDetailsData_product_variants_attributes,
  GProductDetailsData_product_variants_attributes_attribute,
  GProductDetailsData_product_variants_attributes_values,
  GProductDetailsData_product_variants_images,
  GProductDetailsData_product_variants_pricing,
  GProductDetailsData_product_variants_pricing_price,
  GProductDetailsData_product_variants_pricing_priceUndiscounted,
  GProductDetailsData_product_variants_pricing_priceUndiscounted_net,
  GProductDetailsData_product_variants_pricing_price_net,
  GProductDetailsReq,
  GProductDetailsVars,
  GProductErrorCode,
  GProductFilterInput,
  GProductImageCreateInput,
  GProductImageUpdateInput,
  GProductInput,
  GProductOrder,
  GProductOrderField,
  GProductPricingFieldData,
  GProductPricingFieldData_pricing,
  GProductPricingFieldData_pricing_priceRange,
  GProductPricingFieldData_pricing_priceRange_start,
  GProductPricingFieldData_pricing_priceRange_start_net,
  GProductPricingFieldData_pricing_priceRange_stop,
  GProductPricingFieldData_pricing_priceRange_stop_net,
  GProductPricingFieldReq,
  GProductPricingFieldVars,
  GProductStockFilterInput,
  GProductTypeConfigurable,
  GProductTypeEnum,
  GProductTypeFilterInput,
  GProductTypeInput,
  GProductTypeSortField,
  GProductTypeSortingInput,
  GProductVariantBulkCreateInput,
  GProductVariantCreateInput,
  GProductVariantFieldsData,
  GProductVariantFieldsData_attributes,
  GProductVariantFieldsData_attributes_attribute,
  GProductVariantFieldsData_attributes_values,
  GProductVariantFieldsData_images,
  GProductVariantFieldsData_pricing,
  GProductVariantFieldsData_pricing_price,
  GProductVariantFieldsData_pricing_priceUndiscounted,
  GProductVariantFieldsData_pricing_priceUndiscounted_net,
  GProductVariantFieldsData_pricing_price_net,
  GProductVariantFieldsReq,
  GProductVariantFieldsVars,
  GProductVariantInput,
  GReorderInput,
  GReportingPeriod,
  GSaleFilterInput,
  GSaleInput,
  GSaleSortField,
  GSaleSortingInput,
  GSaleType,
  GSearchProductsData,
  GSearchProductsData_products,
  GSearchProductsData_products_edges,
  GSearchProductsData_products_edges_node,
  GSearchProductsData_products_edges_node_pricing,
  GSearchProductsData_products_edges_node_pricing_priceRange,
  GSearchProductsData_products_edges_node_pricing_priceRange_start,
  GSearchProductsData_products_edges_node_pricing_priceRange_start_net,
  GSearchProductsData_products_edges_node_pricing_priceRange_stop,
  GSearchProductsData_products_edges_node_pricing_priceRange_stop_net,
  GSearchProductsData_products_edges_node_thumbnail,
  GSearchProductsData_products_edges_node_thumbnail2x,
  GSearchProductsData_products_pageInfo,
  GSearchProductsReq,
  GSearchProductsVars,
  GSelectedAttributeFieldsData,
  GSelectedAttributeFieldsData_attribute,
  GSelectedAttributeFieldsData_values,
  GSelectedAttributeFieldsReq,
  GSelectedAttributeFieldsVars,
  GSeoInput,
  GServiceAccountFilterInput,
  GServiceAccountInput,
  GServiceAccountSortField,
  GServiceAccountSortingInput,
  GServiceAccountTokenInput,
  GShippingErrorCode,
  GShippingMethodTypeEnum,
  GShippingPriceInput,
  GShippingZoneCreateInput,
  GShippingZoneUpdateInput,
  GShopErrorCode,
  GShopSettingsInput,
  GShopSettingsTranslationInput,
  GSiteDomainInput,
  GStaffCreateInput,
  GStaffMemberStatus,
  GStaffNotificationRecipientInput,
  GStaffUpdateInput,
  GStaffUserInput,
  GStockAvailability,
  GStockErrorCode,
  GStockFilterInput,
  GStockInput,
  GTaxRateType,
  GTransactionError,
  GTransactionKind,
  GTranslatableKinds,
  GTranslationErrorCode,
  GTranslationInput,
  GUUID,
  GUpload,
  GUserCreateInput,
  GUserSortField,
  GUserSortingInput,
  GVariantListData,
  GVariantListData_productVariants,
  GVariantListData_productVariants_edges,
  GVariantListData_productVariants_edges_node,
  GVariantListData_productVariants_edges_node_attributes,
  GVariantListData_productVariants_edges_node_attributes_attribute,
  GVariantListData_productVariants_edges_node_attributes_values,
  GVariantListData_productVariants_edges_node_images,
  GVariantListData_productVariants_edges_node_pricing,
  GVariantListData_productVariants_edges_node_pricing_price,
  GVariantListData_productVariants_edges_node_pricing_priceUndiscounted,
  GVariantListData_productVariants_edges_node_pricing_priceUndiscounted_net,
  GVariantListData_productVariants_edges_node_pricing_price_net,
  GVariantListData_productVariants_edges_node_product,
  GVariantListData_productVariants_edges_node_product_thumbnail,
  GVariantListReq,
  GVariantListVars,
  GVoucherDiscountType,
  GVoucherFilterInput,
  GVoucherInput,
  GVoucherSortField,
  GVoucherSortingInput,
  GVoucherTypeEnum,
  GWarehouseAddressInput,
  GWarehouseCreateInput,
  GWarehouseErrorCode,
  GWarehouseFilterInput,
  GWarehouseSortField,
  GWarehouseSortingInput,
  GWarehouseUpdateInput,
  GWebhookCreateInput,
  GWebhookErrorCode,
  GWebhookEventTypeEnum,
  GWebhookFilterInput,
  GWebhookSampleEventTypeEnum,
  GWebhookSortField,
  GWebhookSortingInput,
  GWebhookUpdateInput,
  GWeightScalar,
  GWeightUnitsEnum,
  G_Any,
  GaccountAddressCreateData,
  GaccountAddressCreateData_accountAddressCreate,
  GaccountAddressCreateData_accountAddressCreate_accountErrors,
  GaccountAddressCreateData_accountAddressCreate_user,
  GaccountAddressCreateData_accountAddressCreate_user_addresses,
  GaccountAddressCreateData_accountAddressCreate_user_addresses_country,
  GaccountAddressCreateReq,
  GaccountAddressCreateVars,
  GaddressDeleteData,
  GaddressDeleteData_accountAddressDelete,
  GaddressDeleteData_accountAddressDelete_accountErrors,
  GaddressDeleteData_accountAddressDelete_user,
  GaddressDeleteData_accountAddressDelete_user_addresses,
  GaddressDeleteData_accountAddressDelete_user_addresses_country,
  GaddressDeleteReq,
  GaddressDeleteVars,
  GaddressUpdateData,
  GaddressUpdateData_accountAddressUpdate,
  GaddressUpdateData_accountAddressUpdate_accountErrors,
  GaddressUpdateData_accountAddressUpdate_user,
  GaddressUpdateData_accountAddressUpdate_user_addresses,
  GaddressUpdateData_accountAddressUpdate_user_addresses_country,
  GaddressUpdateReq,
  GaddressUpdateVars,
  GattributesData,
  GattributesData_attributes,
  GattributesData_attributes_edges,
  GattributesData_attributes_edges_node,
  GattributesData_attributes_edges_node_values,
  GattributesData_attributes_pageInfo,
  GattributesReq,
  GattributesVars,
  GchangePasswordData,
  GchangePasswordData_passwordChange,
  GchangePasswordData_passwordChange_accountErrors,
  GchangePasswordData_passwordChange_user,
  GchangePasswordReq,
  GchangePasswordVars,
  GcreateCheckoutData,
  GcreateCheckoutData_checkoutCreate,
  GcreateCheckoutData_checkoutCreate_checkout,
  GcreateCheckoutData_checkoutCreate_checkoutErrors,
  GcreateCheckoutData_checkoutCreate_checkout_availablePaymentGateways,
  GcreateCheckoutData_checkoutCreate_checkout_availablePaymentGateways_config,
  GcreateCheckoutData_checkoutCreate_checkout_availableShippingMethods,
  GcreateCheckoutData_checkoutCreate_checkout_totalPrice,
  GcreateCheckoutData_checkoutCreate_checkout_totalPrice_gross,
  GcreateCheckoutReq,
  GcreateCheckoutVars,
  GgetAddressesData,
  GgetAddressesData_me,
  GgetAddressesData_me_addresses,
  GgetAddressesData_me_addresses_country,
  GgetAddressesReq,
  GgetAddressesVars,
  GregisterAccountData,
  GregisterAccountData_accountRegister,
  GregisterAccountData_accountRegister_accountErrors,
  GregisterAccountData_accountRegister_user,
  GregisterAccountReq,
  GregisterAccountVars,
  GrequestPasswordResetData,
  GrequestPasswordResetData_requestPasswordReset,
  GrequestPasswordResetData_requestPasswordReset_accountErrors,
  GrequestPasswordResetReq,
  GrequestPasswordResetVars,
  GtokenCreateData,
  GtokenCreateData_tokenCreate,
  GtokenCreateData_tokenCreate_accountErrors,
  GtokenCreateData_tokenCreate_user,
  GtokenCreateReq,
  GtokenCreateVars,
  GupdateBasicDetailsData,
  GupdateBasicDetailsData_accountUpdate,
  GupdateBasicDetailsData_accountUpdate_accountErrors,
  GupdateBasicDetailsData_accountUpdate_user,
  GupdateBasicDetailsReq,
  GupdateBasicDetailsVars
])
final Serializers serializers = _serializersBuilder.build();
